### ISSUE TITLE
Game is asking to always format memory card

### ISSUE THREAD

**Issue by RetroGameTalk** [DOL-Translations/donkey-konga-3#1]
> the game tells me to erase my memory card in the beginning because it is corrupted to create a save (using on original hardware, GC Loader) and I have 2 memory cards, one with Japanese saves and one with US saves, and they work fine, and it tells me the same thing. I can say no and play the game, but every time I want to save, it says the memory card is corrupted and needs formating to save
Issue posted By Elira

**Comment by NewGBAXL** [comment]
This is a known issue, it has to do with the region the game is formatted in not matching the region of the game code.
That is, your loader, GCLoader in this case, loads an NTSC-U Memory Card but the game itself is still expecting NTSC-J.

This can be currently avoided by commenting out the region change in `/src/Main.asm` at `lines 56 & 57`, and then manually running `tools/compile.bat` with your ISO as `/input/Donkey Konga 3 [J].iso`.
```
//Region
//Text($3, "E")
//origin $45B; db $01
```

This has been noted in the description of the prerelease build:
> the game has been formatted to NTSC-U (English) but may cause save issues
as such PLEASE PLEASE PLEASE do not run this game on the same Memory Card (physical or virtual) as other games

**Comment by NewGBAXL** [comment]
@MediaMaquina save data error fixed, the game's titleid & region was hardcoded elsewhere in the rom, alongside savedata for the other DK games. Happy gaming :)
